language: ruby
rvm:
- 2.1.1
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: olDQzWCnGc0tY3qADbosBL0Mad7tREp9BKM5LkvsEWWCD9pHuclOR3HYRgGQDxxImVlEUkfZffVIimq9FRNxvvZsE9nedo93gZjlAAw5cpCG/+wYcIUIhQcPNNR64FZNjqHnst5LSeLEB577vyi22odCSuPRB3RKJryJ21eUITI=
  app: g2-store-staging
  on:
    repo: gSchool/g2-store
  run:
    - "bundle exec rake db:migrate"
